name: Rust Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Clippy
        run: cargo clippy --all-features --workspace -- -D warnings


  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: twitter-dl
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            exe: twitter-dl.exe
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            exe: twitter-dl
            target: x86_64-apple-darwin
          - os: macos-latest
            exe: twitter-dl
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: twitter-dl-${{ matrix.target }}
          path: target/debug/${{ matrix.exe }}

